### ISSUE TITLE
duplicate axis

### ISSUE THREAD

**Issue by ma73es** [alvarob96/investpy#100]
Hi Alvaro.

I have found a duplicate entry when downloading more than 20 years of eur-usd.

![Captura de pantalla 2020-01-20 a las 12 13 52](https://user-images.githubusercontent.com/12106207/72722341-5ec35880-3b7e-11ea-8076-f495410aa130.png)

An easy fix is 
df=df[~df.index.duplicated(keep='last')]
but I think the download is made in bunch of 19 or 20 years and may be the duplication is in the merge process.

**Comment by alvarob96** [comment]
Hi @ma73es!

I solved it shifting the interval range 1 day whenever the difference between `from_date` and `to_date` was higher than 19 years.

Previously the intervals were being split like: `[{'start': '01/01/2000', 'end': '01/01/2019'}, {'start': '01/01/2019', 'end': '01/01/2020'}]` which was including both the last date of the first interval and the first date of the next one, which now has been replaced so that the intervals are: `[{'start': '01/01/2000', 'end': '01/01/2019'}, {'start': '01/02/2019', 'end': '01/01/2020'}]`, in `dd/mm/yyyy` format.
