### ISSUE TITLE
Stock company profile data retrieval for USA listed equities

### ISSUE THREAD

**Issue by js333031** [alvarob96/investpy#103]
I tried different values for country param and omitted country param and can't retrieve the data...

```
>>> company_profile = investpy.get_stock_company_profile(stock='intc', country='united states')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/Finance/my_ib_stuff/ib_flex_query_download_parse/lib/python3.6/site-packages/investpy/stocks.py", line 690, in get_stock_company_profile
    raise RuntimeError("ERR#0034: country " + country.lower() + " not found, check if it is correct.")
RuntimeError: ERR#0034: country united states not found, check if it is correct.
>>> company_profile = investpy.get_stock_company_profile(stock='intc', country='united states')
```

**Comment by alvarob96** [comment]
Hi @js333031!

As it is mentioned in the [Documentation](https://investpy.readthedocs.io/stocks.html#company-profile), there is a Warning stating that the functionality of `investpy.get_stock_company_profile()` is just available for Spanish stocks. Anyways, since you opened this issue, I will be working on it so that company profiles can be retrieved for all the listed stocks if they are available at Investing.com.

Thank you for reporting it! :star: :octocat:
