### ISSUE TITLE
Testing LSE equities: missing data

### ISSUE THREAD

**Issue by lefig** [alvarob96/investpy#108]
Hi there,

I have been doing some testing using my LSE universe list of equities. All the following equities have been successfully located and reported using investpy search. 

However quotes and historical data downloads do not appear to work with the exception being thrown. I have attached a spreadsheet for further details. 

Moreover, I have visually confirmed that the data is actually there and available on investing.com.

It would be great if you were able to investigate further the reason for this and hopefully close the issue.

Thanks
PS - I have attached a file but pls let me know if you can't open 

[failed_investing_symbols.txt](https://github.com/alvarob96/investpy/files/4250795/failed_investing_symbols.txt)

**Comment by lefig** [comment]
Excellent news. Much obliged too. 
Its an excellent project.

**Comment by alvarob96** [comment]
Hi again @lefig!

Thank you for reporting this issue! After some research I developed [this Jupyter Notebook](https://github.com/alvarob96/investpy/files/4265966/not_found_stocks.pdf), which I send you in PDF format. As you can see, __some stocks were not found among _investpy's static data_ and others were not even found among _Investing's data___ (from the last mentioned we can do nothing about it).

![not_found_stocks](https://user-images.githubusercontent.com/36760800/75522582-9d182700-5a0a-11ea-9d8a-88dc224af8e0.gif)

So on, I encourage you to use `investpy.search_stocks()` functionality which is also available for every other financial product such as `invesypy.search_etfs()` where the function structure is as it follows `investpy.search_` plus the financial product name (in plural). Additionally, if the financial product you are searching is not even available among investpy's static data, you can use `investpy.search()` function which uses the inner Investing's search engine, providing an additional value since if the financial product is not indexed among investpy's static data it means that it is not indexed in Investing tables, so that it can just be accessed using the search engine.

All the presented functionality has been developed and briefly explained in the Jupyter Notebook I sent you, but if you have any other doubt or issue feel free to ask me!

Regards,
Álvaro Bartolomé.

**Comment by lefig** [comment]
Hi Alvaro,

That would be splendid. I will be sure to test the fix and the above kindly prepared notebook today. Performance is good btw. I hope that you don't mind if I have any further queries. 

But in the mean time, thank you.

Fig
