### ISSUE TITLE
Question: Search functionality

### ISSUE THREAD

**Issue by lefig** [alvarob96/investpy#112]
Hi there,

Thank you for addressing the recent LSE missing data issue. I appreciate that.

I have a follow up query and I hope that you don't mind.

When performing a search of a London listed fund or share name (assuming that I don't know the symbol name on Investing) do both the stocks.search_stocks and more generic investpy.search look for a name using an exact match or identify similar product names. 

What is best practice name to use for search - say just the first two words of a complete listing name?

Thank you

Fig

**Comment by alvarob96** [comment]
Hi again @lefig,

the function `investpy.search_stocks()` searches among **investpy**'s static data and the search results are the matches between the introduced text and the original one, using the `__contains__` function, e.g. if you search `investpy.search_stocks(by='name', value='pple')` will return the APPL (Apple) stock.

While the function `investpy.search()` uses Investing.com inner search engine so that it is managed by Investing.com. But, applied to the previously mentioned example, the function call `investpy.search(text='pple')` will return no results.

Hope this was clear enough! Anyways, I am planning on including more usage samples in the documentation which can be found at https://investpy.readthedocs.io/.
