### ISSUE TITLE
Function to create the .csv files ?

### ISSUE THREAD

**Issue by JuCarm** [alvarob96/investpy#113]
Hello,
I've been browsing the investpy code some, but I do not seem able to find the function that creates the .csv files (country and bonds, stocks, etfs...) from requests to investing.com, so as to ensure we always have up-to-date .csv files.
Can you point me to that piece of code ?
Thanks.

PS. investpy_portfolio is not up to date vis-a-vis investpy, and so will not work out of the box (uses equity instead of stock, uses stock_name instead of stock_symbol, etc.). I have been able to make the minor changes so that it works again.

**Comment by alvarob96** [comment]
Hi @JuCarm! 

As it was mentioned in 301bb934948131818f94b618131c98d3cb981e3b, the static data retrieval functionality is no longer part of investpy's functions since it does not provide any value as those functions take too long to execute and are not intended for user's usage. So on, I keep the static data retrieval scripts for my own as previously stated.

Additionally, any issue related with either [trendet](https://github.com/alvarob96/trendet) or [investpy_portfolio](https://github.com/alvarob96/investpy_portfolio) should be reported on their respective repositories.

As you reported it, I will wait until you create the issue in [investpy_portfolio](https://github.com/alvarob96/investpy_portfolio) repository so that Github notices that you are the one that proposed/reported the issue. As additional information, I will be including more functionality to **investpy_portfolio** the following months, so feel free to propose any new enhancement.

Hope this helped you! :star: :octocat:

**Comment by alvarob96** [comment]
Hi @JuCarm! Just let you know that I am going to start working again on investpy_portfolio functionality since I will do a huge refactoring of the project. So I encourage you again to open the issue you mentioned me at: https://github.com/alvarob96/investpy_portfolio/issues
