### ISSUE TITLE
development of raw materials retrieval

### ISSUE THREAD

**Issue by Djaramillo39** [alvarob96/investpy#37]
In addition to the existing functionalities, could it be possible to include the raw materials retrieval (Ex. Brent oil).

Thank you for your help!

**Comment by alvarob96** [comment]
Hi @Djaramillo39! As far as I have researched over Investing.com commodities, I was not able to determine which is the exact webpage to retrieve data from since Investing.com displays a lot of different data on Commodities.

I think that the commodities you are asking for are the ones from the following sectors: _Metals, Softs, Meats, Energy and Grains_. Anyways Investing.com also provides data such as: _Real Time Commodities, Comodity Indices or Futures Specifications_, so I want you to confirm which data are you aiming for retrieval.

Currently, the retrieval of _Metals, Softs, Meats, Energy and Grains_ commodities data is being developed, but before launching the new **investpy** release I want you to tell me if there is any valuable missing data when it comes to commodity data retrieval.

Thank you! :star: :octocat:

**Comment by alvarob96** [comment]
Hi @Djaramillo39, just to let you know that I am currently working on it, so that in the 0.9.10 version of **investpy** commodities are available for retrieval. As I already told you in the previous commentary, the commodities retrieval will carry the retrieval of *Metals, Softs, Meats, Energy and Grains*.

Thank you for your patience! :star: :octocat:
