### ISSUE TITLE
get_historical_data() - bug

### ISSUE THREAD

**Issue by Djaramillo39** [alvarob96/investpy#38]
I believe get_historical_data() has a bug.

I did a test comparing the same equity (Exxon Mobil) using get_recent_data() and get_historical_data(), both for the same time frames, and got different values.

![test](https://user-images.githubusercontent.com/45964127/65347063-6f6abe80-dbde-11e9-97b2-bc9fb22f40ef.JPG)

Then I tested another equity (DOW) with get_recent_data() and was getting the exact same values as for the get_recent_data("Exxon Mobil").

**Comment by alvarob96** [comment]
Thank you @Djaramillo39! 

I did some checks and I realised this error was due to a missing input param conversion, since equities check was done via converting every available equity to lower case and the input `equity` was not properly converted so the `investpy.get_historical_data()` function was returning the first `pandas.DataFrame` row of data since there were no matches.

For example, in the use case you are showing, whenever you were aiming to retrieve historical data from **Exxon Mobil** equity from the _United States_, the function was first retrieving the equities `pandas.DataFrame` from the _United States_ and then looking for _Exxon Mobil_ which had no matches since all the names from the dataset where before converted to lower case so the comparison: `'exxon mobil' == 'Exxon Mobil'` was not matching since the str comparison is case-sensitive.
