### ISSUE TITLE
Funtion to scrape data of Stoxx 600 and Dow Jones supersectors and subsectors 

### ISSUE THREAD

**Issue by gerardorc85** [alvarob96/investpy#42]
Hi Alvaro,

Would be possible for you to incorporate an additional functionality to the existing code? I'm interested in scraping data from the Stoxx 600 and Dow Jones sectors and subsectors since these are the ones I use in my trading and backtests. 

Tickers of the Stoxx 600 subsectors are as follows:

['SXEP','SX4P','SXPP','SXOP','SXNP','SXAP','SX3P','SXQP','SXDP','SXRP','SXMP','SXTP','SKXP','SX6P','SX7P','SXIP','SX86P','SXFP','SX8P']

Tickers of some of the Dow Jones sectors/supersectors are:

['DJUSEN','DJUSCH','DJUSBS','DJUSCN','DJUSIG','DJUSAP','DJUSFB','DJUSNG','DJUSHC','DJUSRT','DJUSME','DJUSCG','DJUSTL','DJUSUT','DJUSBK','DJUSIR','DJUSRE','DJUSFI','DJUSTC']

Thanks in advance,
Gerardo

**Comment by alvarob96** [comment]
Hi @gerardorc85! 

I am currently working on this and some other features/improvements, but just to let you know, I already solved this issue. Anyways you need to wait until the new release is out (probably this week), as it will include the new features and updates so you can retrieve data from both subsectors and supersectors such as *DJUSEN or SX86P*, among others.

Note that all the symbols you mentioned above are going to be supported by **investpy** for its retrieval!

Make sure to be watching the repo to be notfied whenever a new release is out! Thank you for your support and patience! 👀

**Comment by alvarob96** [comment]
⭐️ **0.9.6 investpy release is out!** ⭐️ 

Now you can retrieve more indices as the ones you requested before, since in the previous release some indices were not available for retrieval as the comple indices listing was not retrieved.

An example is proposed below in order to search indices by their symbol via investpy:

![stoxx600 symbols](https://user-images.githubusercontent.com/36760800/66104499-0b220480-e5b9-11e9-8e09-3c1565d400af.JPG)

![dow jones symbols](https://user-images.githubusercontent.com/36760800/66107106-bd5cca80-e5bf-11e9-89d7-7f0fb08bd735.JPG)

Note that both SKXP and SX86P indices are not indexed in investpy, due to an Investing.com indexing error which will be solved in the next release fix really soon.

**Comment by alvarob96** [comment]
@gerardorc85 note that this issue has already been solved in #50, where the issue has been identified since it is an Investing.com error and, so on, it has been solved for indices. As nor just indices information was not complete, also ETFs have missing information as reported in #31. 

All this updates will be release whenever they all are identified and fixed! Make sure to be watching the repo in order to get notified when the new release is out!

**Comment by gerardorc85** [comment]
@alvarob96 thanks a lot for the latest improvements and developments, they are making my life way way easier ;-)
Just tested the function for the American DJ subsectors and works perfect, but for some reason for the  European ones (besides de problem you mentioned above for SKXP and SX86P) has some issue recognizing the country as "euro zone" . 
Any clue of what the reason can be?   See function and error below:

**index = investpy.get_index_historical_data(index='STOXX Europe 600 Utilities',country='euro zone',from_date='01/01/1934',to_date='01/10/2019')**

**RuntimeError: ERR#0034: country euro zone not found, check if it is correct.**

![image](https://user-images.githubusercontent.com/55779669/66182695-69f98380-e676-11e9-9d58-55b46ad3bd1c.png)

Thanks,
Gerardo

**Comment by alvarob96** [comment]
Hi @gerardorc85! 

Thank you for reporting a mes issue, but un order to keep the project organized, do you mind open a new issue please? I am asking you this since this issue is already closed! 

Thanks a lot! :star:

**Comment by alvarobartt** [comment]
@marineanalytica Sorry for taking so long to solve this issue even though it was easy to fix but I though it was already fixed 😩

To install the latest version with this bug fix as well as some other fixes, please install it as it follows:

```
pip install investpy==1.0.3
```

Remember to star the repository, follow me here at https://github.com/alvarobartt and on Twitter at https://twitter.com/alvarobartt so as to get notified about all the updates and projects I'm working on! :star: :octocat:
