### ISSUE TITLE
how can I find VIX index?

### ISSUE THREAD

**Issue by KAIMAN0** [alvarob96/investpy#47]
which function can i use to find VIX index from CBOE? Also which country does the VIX belongs to? Should I use USA or america or united states?

**Comment by alvarob96** [comment]
Hi @KAIMAN0! 

Since the previous releases of [investpy](https://github.com/alvarob96/investpy), in particular as described in [0.9.4](https://github.com/alvarob96/investpy/releases/tag/0.9.4) release notes, where the **search functions** for equities, funds and etfs was developed. Now, since the [0.9.5](https://github.com/alvarob96/investpy/releases/tag/0.9.5) where some index data retrieval errors were fixed, the search functions were also implemented when it came to index search among all the data indexed in **investpy**, so you can do the following in order to search an index and then retrieve its data:

![VIX Index Data Retrieval](https://user-images.githubusercontent.com/36760800/65888554-01718480-e3a0-11e9-87ee-6d688e055421.png)

Hope this answer/piece of code was useful for you! Please, make sure to star the repo! ⭐️ :octocat:
