### ISSUE TITLE
Bond queries

### ISSUE THREAD

**Issue by aaronmkchan** [alvarob96/investpy#52]
Hi Alvaro, thanks again for a great tool!

Was wondering if you could include other asset classes in the queries, namely bonds and perhaps even commodities if you have the time.

**Comment by alvarob96** [comment]
@aaronmkchan since **commodities data retrieval** has already been requested in issue #37, its retrieval will be updated in the next release, since it has priority.

Anyways, **investpy** is intended to cover all the data available in Investing.com, so on, the retrieval of all the financial products is going to be done.

Make sure to be watching the repo in order to get notified whenever a new release is out!

**Comment by alvarob96** [comment]
Hi @aaronmkchan! As you may have noticed, bonds information has been retrieved and already implemented in **investpy** usage. The new features (including this one) will be available in next investpy's release. So on, make sure to be watching the repo in order to get notified whenever the new release is out! ⭐️ :octocat:
