### ISSUE TITLE
Can use investpy for Singapore stocks?

### ISSUE THREAD

**Issue by GMZ21931** [alvarob96/investpy#59]
Hi @alvarob96,

Great job in creating this Python package!

In trying to get Singapore stocks, I tried:

`import investpy`
`df = investpy.get_stock_recent_data(stock='Z74.SI', country='Singapore')`
`print(df.head())`

It gives:
`RuntimeError: ERR#0018: stock z74.si not found, check if it is correct.`

Changed the stick to ‘Z74’ only, and it's the same.

What's the right way to put stock stickers to Singapore? 
(btw, is there a way to search all stock stickers of a country?)

Thank you.

p.s.
Z74 is a valid stock, https://www.investing.com/equities/singapore-telecommunications.

**Comment by alvarob96** [comment]
Hi @GMZ21931! 

Since I do not know how Singapore stocks work, I am using the symbol specified by Investing.com, in the case you are asking for: https://www.investing.com/equities/singapore-telecommunications, the symbol I am using is **STEL** which I do not know if it is or is not the symbol, because there is also a field called *S/N* whose value is **Z74**.

Anyways, if **STEL** is not the symbol for the stock you are asking for, I will appreciate you to tell me where is the Singapore stock symbol placed in Investing.com in order to retrieve and correct the information indexed in **investpy**.

You can use the function ``investpy.get_stocks_list(country='singapore')`` which will return a list containing all the stock symbols available in Singapore. You can also search for a stock by its name for example and retrieve the symbol with the function ``investpy.search_stocks(by='full_name', value='Singapore Telecommunications')``. 

Currently the piece of code to retrieve the recent/historical data from the stock you are asking for will look like:

```python
import investpy

recent = investpy.get_recent_data(stock='STEL',
                                  country='singapore')
print(recent.head())

historical = investpy.get_stock_historical_data(stock='STEL',
                                                country='singapore',
                                                from_date='01/01/2010', 
                                                to_date='01/01/2019')
print(historical.head())
```

Thank you for your support! Make sure to star and watch the repo to be notified about all conversations! :star: :octocat:

**Comment by GMZ21931** [comment]
Hi @alvarob96 ,

Thank you so much for the detailed explanation and sharing.  It is spirit like yours make this world so beautiful, and people benefit from knowledge sharing!

The stock sticker, where also Singapore Stock Exchange, and Yahoo also using is Z74. It is called S/N	Z74 on the investing.com, as a tag below ISIN: SG1T75931496.

Much appreciated this can be added into your package so could be widely used by others.

Thanks again for the attention on this question.

Of course I must star this marvelous work!

**Comment by alvarob96** [comment]
Thank you for your support @GMZ21931! 

I have been trying to figure it out and I finally decided to leave the current symbol. So this issue won't be fixed now since it takes more research and I need to find the proper way to do it without breaking anything! So sorry for that, but I try it.

Anyways, as I already explained you, for now you can use the Investing.com symbol for every stock, in the example you asked for in the initial issue, the symbol for *Singapore Telecommunications Ltd* is *STEL*. You can either use the functions: `investpy.search_stocks(by, value)` or `investpy.get_stocks(country)`, to search an specific stock by any available value or to get the `pandas.DataFrame` with all the stocks from any country to search on in manually, respectively.

Thank you! :star: :octocat:

**Comment by GMZ21931** [comment]
@alvarob96, thank you for looking into the question.

again, great work. it contributes to human's welfare and world economy!

all the best with projects!
