### ISSUE TITLE
Does not work correctly on bonds of countries with a space

### ISSUE THREAD

**Issue by SuperCuber** [alvarob96/investpy#62]
When running `investpy.bonds.get_bonds("hong kong")` an empty dataframe with the columns `country, name, full_name` is returned. This also happens for the following countries:

`['czech republic', 'hong kong', 'new zealand', 'south africa', 'south korea', 'sri lanka']`

I noticed that all of them have a space in the name, is this a problem with the package?

**Comment by alvarob96** [comment]
Hi @SuperCuber!

First of all thank you for reporting the issue! As you previously described, countries with an space (' ') fail when retrieving bonds, this issue is related to the inner information retrieved from Investing.com. So on, this issue will be fixed as soon as possible and a new investpy version will be released.

Thank you! If you find any other bug or have any other suggestion feel free to open as much issues as needed. Make sure to star the repo if you find it useful! ⭐️ :octocat:

**Comment by SuperCuber** [comment]
@alvarob96 Hello, when do you estimate the new version to be published? I'd like to use this in a project. Thanks for the great work :)

**Comment by alvarob96** [comment]
Hi @SuperCuber! 

The new version will be released this week, probably tomorrow or the day after tomorrow not sure.

Thank you for your support! :star: :octocat:
