### ISSUE TITLE
Implement the possibility to retreive non-daily TF data

### ISSUE THREAD

**Issue by davetromp** [alvarob96/investpy#64]
Investing provides daily, weekly and monthly timeframe data. I believe that currently the daily timeframe is hardcoded. For example, in the get_recent_data function in the __init__.py file parameters are set as follows:
`    params = {
        "curr_id": id_,
        "smlID": str(randint(1000000, 99999999)),
        "header": header,
        "interval_sec": "Daily",
        "sort_col": "date",
        "sort_ord": "DESC",
        "action": "historical_data"
    }`

We could possibly make the interval_sec an optional parameter, where Daily is the default.

**Comment by alvarob96** [comment]
Hi @davetromp! 

Thank you for the proposed enhancement, I will work on it asap since now I am figuring out how to make the package more usable and fix the previously reported issues. So on, once **investpy 0.9.9** is released, this issue will be worked on.

Anyways thank you for reporting it! :octocat:
