### ISSUE TITLE
stocks.py issue

### ISSUE THREAD

**Issue by MPrazzoli** [alvarob96/investpy#67]
I faced an issue during the search of stock prices through the following script:

import investpy

df = investpy.get_stock_historical_data(stock='apple',
                                        country='united states',
                                        from_date='01/01/2010',
                                        to_date='01/01/2019')
print(df.head())

Actually, for each stock different from 'BBVA' I get the following error:
line 520, in get_stock_historical_data
    raise RuntimeError("ERR#0018: stock " + stock + " not found, check if it is correct.")
RuntimeError: ERR#0018: stock houghton mifflin not found, check if it is correct.

![bbva](https://user-images.githubusercontent.com/52362087/68542853-c441de80-03b0-11ea-98b6-b35aab39a173.PNG)
![apple](https://user-images.githubusercontent.com/52362087/68542856-c60ba200-03b0-11ea-9d49-251991570f7e.PNG)

**Comment by alvarob96** [comment]
Hi @MPrazzoli!

Since version 0.9.7 **stock retrieval now takes the stock symbol as input parameter instead of the stock name** as the symbol is ease to know/use for the user when retrieving stock information. This was updated in a previous version, but it was my bad not to display a _DeprecationWarning_ so to let the user know that it was about to be changed.

Anyways, now you can either use the symbol as input if know, or retrieve the symbol from investpy as described below or use the `investpy.search_stocks(by='name', value='stock_name_to_search')` function.

```python
import investpy

stocks = investpy.get_stocks(country='united states')

stock_name = 'Apple'
symbol = stocks.loc[(stocks['name'].str.lower() == stock_name.lower()).idxmax(), 'symbol']
```

_NOTE that the previous symbol search function will retrieve a result even if the introduced stock name was not found (which is obviouslñy not the optimal way of doing it), so please check that the retrieved stock symbol is the correct one. If not, you can always use another `pandas.DataFrame` search operator or use the **investpy** function to search stocks as preciously mentioned._
