### ISSUE TITLE
retrieving data for stock which is no longer listed

### ISSUE THREAD

**Issue by walterfm** [alvarob96/investpy#69]
I would like to retrieve data
for the Brazilian company OGXP3, which
is long gone. If I search for it in investing.com
I find its historical data. See
https://br.investing.com/equities/ogx-petroleo-on-nm

However, if I try
investpy.get_stock_historical_data(stock='ogx-petroleo-on-nm',country='brazil' ...)
or
investpy.get_stock_historical_data(stock='ogxp3',country='brazil' ...)

I get  "ERR#0018: stock ogxp3 not found, check if it is correct."

**Comment by alvarob96** [comment]
Hi @walterfm!

I already checked what you are asking for and the stock with symbol OGXP3 does not appear among Investing.com data. Not even on the search bar, so on, **that information can not be retrieved using investpy**.

The message Investing.com displays is the following one:  `OGX PETROLEO ON is no longer active, quotes are not updating` so on, its data can not be retrieved since that stock is no longer indexed in Investing.com stock listing.

So on, **this issue will not be worked on now since it has no solution**, anyways I will try to find out how to retrieve data that is no longer indexed in Investing.com public stock listing.

Thank you! Make sure to star the repo if you found it useful! :star: :octocat:

**Comment by walterfm** [comment]
Hi Alvaro,

   Thanks to looking at this.

   I believe the message by investing.com is misleading.

   I just retrieved the data manually (see the enclosed csv file)
and it is certainly available at investing.com.

   Anyway, this issue is not that important and you certainly
have more relevant stuff to care about.

         regards,

               walter.

**Comment by alvarob96** [comment]
Hi @walterfm!

Maybe I will find out how to solve this soon, but now I do not know how to proceed on financial products which are no longer supported by Investing.com even though its data seems to be still indexed in Investing.com.

Thank you for reporting this issue!

**Comment by walterfm** [comment]
Alvaro,

   I am looking at your code (it is very clear) and I
will try to find a way to handle this.

   If I find something useful I will let you know

      walter.

**Comment by walterfm** [comment]
Alvaro,

   The solution below is good enough for me.
Basically, I search for 'https://www.investing.com symbol'  in
google and from there I guess a tag for the given symbol.
Given the tag, I open 'https://www.investing.com/equities/' + tag
and obtain a guess for the symbol's id.
   With the id and the tag I can get all I need using your api.

Here is the code (is not as clean and well written as yours,
but it suffices for me)

 I am new to python and learned from your code.
Thanks,

             walter.

def guess_tag(symbol):
  tag = None
  header = 'https://www.investing.com/equities/'
  header_len = len(header)
  for url in search('www.investing.com ' + symbol, stop=20):
    idx = url.find(header)
    if idx == 0:
      if tag is None:
        tag = url[header_len:]
      else:
        new_tag = url[header_len:]
        if len(new_tag) < len(tag):
          tag = new_tag

  url = "https://br.investing.com/equities/" + tag
  head = random_head()
  req = requests.get(url, headers=head)
  key = 'dialog-attach-chart_'
  idx = req.text.find(key)
  idx = idx + len(key)
  end = req.text.find('"', idx)
  return [tag, req.text[idx:end] ]
