### ISSUE TITLE
Stock Available in each country

### ISSUE THREAD

**Issue by sea98745** [alvarob96/investpy#70]
As what I found out, the stock list for each country is outdated. Would like to know is is possible to provide the function to get the latest stock list available for each country ? or how to update or get the up to date  stocks.csv ?

**Comment by alvarob96** [comment]
Hi @sea98745!

I am currently working on it so that the updated file is hosted on a public server so that the package updates automatically.

Anyways, could you tell me which stock or stocks are missing?

Thank you for reporting the issue, in the next release (probably by the end of this week) I will generate the new `stocks.csv` file with the updated information which will be included in that release. 

Thank you again! Make sure to star the repository if you found it useful! :star: :octocat:

**Comment by sea98745** [comment]
Hi there,
Thanks for the quick response. At the moment, I did look at the Malaysia
stock market and I notice that the stock.csv file only have 786 entries and
I using investing.com feature, I found that it has 929 entries.

**Comment by alvarob96** [comment]
Yes @sea98745! You are right, I already checked it and I also retrieve up to 929 stocks from Malaysia that is because a minor error on the retrieval scripts.

Thank you for reporting it, I already fixed and **all the investpy resources are being generated again so to include all the missing data and to update the existing one!**

I will let you know whenever it is all done and the new version is released.

**Comment by sea98745** [comment]
Thanks for the fixed.

**Comment by sea98745** [comment]
Hi Alvaro,

Would like to know in future release, are you going to included the
function to generate the stock.csv file ?

**Comment by alvarob96** [comment]
**No, that script will not be available from investpy since the retrieval process is intended to be invisible for the user**. So on, I will generate the data and upload it to a public server from where data can be retrieved either manually or automatically (using investpy functions).

The main reason why data generation scripts will not be available is due to the fact that it is a long process to scrape all the data from Investing and it must be consistent, so on it is not a simple/fast process which you can easily execute. So on, this will not be available.

Anyways, stay tuned since as soon as possible I will release a new investpy version with some interesting features, improvements and some bug fixes! Thank you @sea98745!

**Comment by sea98745** [comment]
In your stock.csv file, could you add the stock code too ?

**Comment by alvarob96** [comment]
Hi @sea98745!

The new investpy release 0.9.11 is out! In this release all the issues have been fixed, including the one you described here. So you can now update the package via pip using: `pip install investpy==0.9.11`.

Thank you! ⭐️ :octocat:
