### ISSUE TITLE
Intraday historical data

### ISSUE THREAD

**Issue by rdoktor** [alvarob96/investpy#79]
Dear Alvaro,
Do you know if it is possible to get Historical data with a 1mn period, Thanks in advance.
Best regards,
Reynald

**Comment by alvarob96** [comment]
Hi @rdoktor, as you may have noticed Investing.com does not provide intra-day data, so its retrieval is not possible now since Investing.com limitations.

I am currently working on a real-time data retrieval function so that that function can be constantly receiving information and storing it during a period of time so that you can generate intra-day data launching the stream. Anyways I am having some issues on its development, so I can not ensure you when this function will be available on investpy.

Make sure to star and be watching the repo so to get all the updates and insights! :star: :octocat:
