### ISSUE TITLE
socks5

### ISSUE THREAD

**Issue by kuhytitusdlz** [alvarob96/investpy#80]
hi, is it possible to setup Socks5 Proxy?
example: socks5h://localhost:9050

**Comment by alvarob96** [comment]
Hi I do not know what do you mean exactly, could you please explain your idea/proposal in greater detail?

**Comment by kuhytitusdlz** [comment]
To connect to the Internet via proxy, like:
telegraph._telegraph.session.proxies = {'https':'socks5h://localhost:9050'}
or
REQUEST_KWARGS = {'proxy_url': 'socks5h://127.0.0.1:9050',}
updater = Updater(token=TOKEN, request_kwargs=REQUEST_KWARGS, use_context=True)

**Comment by alvarob96** [comment]
Well, currently **investpy does not have proxy support** since it is not needed in Investing.com when it comes to avoid HTTP connection errors due to multiple requests from the same IP (fixed using different User-Agent values).

Anyways, one of the future improvements in investpy is to allow the user to set proxies in order to retrieve content from Investing.com, but for now it is not available.

So if you want to contribute on the development of this issue, please include above the required details so to implement proxy usage on requests sent to Investing.com, explaining how will the proxies be used, insights on what is _Stocks5_, advantages of using proxies, any further detail on their usage and implementation, etc.

Thank you for reporting this issue! It will be worked on in future releases, so I will be closing this issue for now and tag it as **wontfix** since it is not going to be worked on now.
