### ISSUE TITLE
Can't access commodity with a non unique name

### ISSUE THREAD

**Issue by mdarblade** [alvarob96/investpy#81]
As far as I've seen, there's no way with the get_commodity_historical_data to get the values for UK copper and USA copper commodity. 

investpy.commodities.get_commodity_historical_data('Copper', '01/10/2019', '13/12/2019')

**Comment by alvarob96** [comment]
Hi @mdarblade!

I made a mistake in a previous issue (64216d522e01c0325fb92f2de2267fe7af1db8a8) when developing the commodities recent/historical data retrieval since I though that there were no duplicated commodities in different countries. I will fix this as soon as possible so that the **country can be specified whenever there is more than one commodity with the same name in different countries** so that the `country` parameter just needs to be specified if there are multiple commodities so to keep this function usage simple to ease it.

Thank you for reporting this issue, please star the repo if you found it useful! :star: :octocat:

**Comment by alvarob96** [comment]
Hi @mdarblade! 

The new investpy release 0.9.11 is out! In this release all the issues have been fixed, including the one you described here. So you can now update the package via pip using: `pip install investpy==0.9.11`.

Thank you! ⭐️ :octocat:
