### ISSUE TITLE
Missing Sweden bonds in the bonds.csv file

### ISSUE THREAD

**Issue by mdarblade** [alvarob96/investpy#86]
Is there a way to refresh those files manually?

**Comment by alvarob96** [comment]
Hi @mdarblade! 

Could you please send me the Investing.com URL of the missing bonds? Since the data that is being used in investpy comes from Investing.com, so I will need you to be more concise in order to include its retrieval on investpy if it is missing.

As far as I was able to check, Investing does not provide any swedish bond as it can be seen in the following URL: https://www.investing.com/rates-bonds/sweden-government-bonds?maturity_from=40&maturity_to=280.

Anyways, note that I implemented a function called `investpy.search_text(text, count=None)` which can be used to search financial products indexed in Investing even though I did not retrieve its data. This function is mainly based on Investing.com search API, so this function provides all the data available in Investing.

You can check its functionallity in the following gist: https://gist.github.com/alvarob96/0b3d48b1d6360c6a0ebd6a64c49c6a2c

Anyways I will fix some issues related to `investpy.search_text()` function which have been recently spotted, so I suggest you to wait until 0.9.12 release is out (probably on 18/12/2019).

Thank you! :octocat:

**Comment by mdarblade** [comment]
Sorry, you're right! The Sweden bonds are not active anymore.

Thank you for the information!
