### ISSUE TITLE
Scraping technical indicators information

### ISSUE THREAD

**Issue by dernat71** [alvarob96/investpy#91]
Hello Alvaro !

First of all, thank you very much for the work you're doing on `investpy` ! It's a really nice library you produced there !

I was exploring the documentation and wondered if you would find interesting to implement the scraping of the technical indicators values (+ buy/sell signals) we can, for example, find [here](https://www.investing.com/equities/cdproject-technical?cid=973319) for each stock 

Have a good day !

Nathan

**Comment by dernat71** [comment]
(corrected my first message since it contained lots and lots of typo haha)

**Comment by alvarob96** [comment]
Hi @dernat71!

Thank you for your idea, I will take it into consideration since I wanted to include Technical Indicators such as *Momentum Indicators* among investpy functions. Anyways I did not come up with the best way of doing it, since even though Investing.com provides the results of the indicators, I was also checking another Python libraries to calculate them such as [TA-Lib](http://ta-lib.org/) or similar, so to differentiate the data retrieval with the calculations.

Currently I do not plan working on this issue, but stay tuned since I will work on this once I release the 0.9.13 investpy version later this week. So maybe in a couple weeks this functionality will be included.

Thank you for your kind words and support! :star: :octocat:

**Comment by alvarob96** [comment]
@dernat71 stay tuned for future updates since this functionality is intended to be included in investpy's 0.9.14 new release.
