### ISSUE TITLE
Append new data set in a CSV existing file

### ISSUE THREAD

**Issue by delta-300** [alvarob96/investpy#92]
Hi Alvaro, 

I edited the post because I want to be clearer with the support request

I usually storing the old CSV investpy downloaded data in a list and then deleting the old csv file and creating it again with the new updated data set.

I wanted to know how can you append a new row updated investpy data to the old csv file each time I run the script?

--

Hola Alvaro,

He editado la publicacion porque queria ser mas claro con la solicitud de ayuda

Normalmente estoy guardando los datos descargados de investpy en una lista y luego borro el archivo CSV antiguo y lo creo de nuevo con el nuevo conjunto de datos actualizado, y pienso que es un proceso muy engorroso.

Queria saber si puedes añadir una nueva fila actualizada de datos a los archivos CSV existentes cada vez que se ejecute el script?

**Comment by alvarob96** [comment]
Hi @delta-300!

I have seen that you already closed this issue so I guess that you already find a solution or discarded it. If you found the solution I will suggest you to post the piece of code in a comment in this issue so that any user with this doubt or question can check it.

Thank you! :star: :octocat:
