### ISSUE TITLE
Investpy Error

### ISSUE THREAD

**Issue by delta-300** [alvarob96/investpy#93]
Hi Alvaro, 

I tried to run a script to get a list of indexes but I don't know why it doesn't work.

Why is that?

Traceback (most recent call last):
  File "indexes.py", line 13, in <module>
    result = investpy.get_index_historical_data(index=product, country=country, from_date='01/01/2001', to_date=d1, interval=interval, order='descending')
  File "/usr/local/lib/python3.8/dist-packages/investpy-0.9.12-py3.8.egg/investpy/indices.py", line 504, in get_index_historical_data
RuntimeError: ERR#0045: index us dollar index not found, check if it is correct.

**Comment by delta-300** [comment]
I've been trying to get the commodity data for the following list even though the api doesn't recognize some instruments and i tried to enter the names in many ways.

For example:
I usually got this error in the terminal: RuntimeError: ERR#0079: commodity oil not found, check if it is correct.

Even so I'll leave the outcome of the list to those who are ok and wrong and I hope you can help me.

XAGEUR (GOLD EURO) =  ERROR
XAGUSD (GOLD DOLLAR) = OK
XAUAUD (GOLD AUSTRALIAN) = ERROR
XAUEUR (GOLD EURO) = ERROR
XAUUSD (SILVER DOLLAR) = OK
XBRUSD (BRENT DOLLAR) = 
XNGUSD (GAS DOLLAR) = OK
XPDUSD (PALLADIUM DOLLAR) ERROR
XPTUSD (PLATINUM DOLLAR) = OK
XTIUSD (OIL DOLLAR) = OK

COCOA = ERROR
COPPER = ERROR
COTTEE = ERROR
COTTON = ERROR
ORANGE = ERROR
SUGAR = ERROR

**Comment by delta-300** [comment]
At the moment the forex script runs pretty well and wanted to make the same for a list of commodities indices and bonds.

The idea is to re-build a script where investpy recognizes such list and I'll leave the script with you so you can analyze it in more detail.

For indexes:

import investpy
from datetime import date
today = date.today()
d1 = today.strftime("%d/%m/%Y")

products = ['ftse 100', 'ibex 35', 'nikkei 225', 'ftse mib', 'hang seng', 'dax', 'cac 40', 'euro stoxx 50', 's&p/asx 200', 'ftse china 50 hkd']
countries = ['united kingdom', 'spain', 'japan', 'italy', 'hong kong', 'germany', 'france', 'germany', 'australia', 'china']
intervals = ['Daily', 'Weekly', 'Monthly']

for product in products:
	for country in countries:
		for interval in intervals:
			result = investpy.get_index_historical_data(index=product, country=country, from_date='01/01/2001', to_date=d1, interval=interval, order='descending')
			result.to_csv(path_or_buf=product.replace('/', '') + '_' + interval + '.csv')

**Comment by alvarob96** [comment]
HI @delta-300! 

The following pieces of code (written in a Jupyter Notebook) will show you which products are available and which are not, so that you can understand **investpy's** usage.

---

**Question 1**: US Dollar Index not found

In order to get to know which indices are available among investpy's static data, you can use `investpy.search_indices()` function and search the index name you want to. In this case, as shown below, the *US Dollar Index* is just available on the United States. So, introducing a country different than the United States will raise an error as you presented above.

![issue93q1](https://user-images.githubusercontent.com/36760800/72431676-b2582f80-3795-11ea-93fe-61f31aded97f.png)

Anyways, if you know that the information exists even if it is not stored among investpy's static data, you can use `investpy.search()` function in order to retrieve Investing.com information from its search engine results as presented below. 

![issue93q11](https://user-images.githubusercontent.com/36760800/72431635-9ce30580-3795-11ea-89e4-7e205b7f28e3.png)

Please read `investpy.search()` documentation so to get to know how to use that function which uses Investing.com search engine to allow users to retrieve information that it is not statically indexed in **investpy**. Additionally. note that the returned `investpy.search_obj.SearchObj` class instances allow you to retrieve both recent and historical data from the resulting product. Reference: https://investpy.readthedocs.io/search_api.html

---

**Question 2**: Oil commodity not found
 
Just as previously described, you can either use the function that searches among investpy's static data (from any financial product) which is `investpy.search_commodities()` or the function to search among all Investing.com data using its search engine which is `investpy.search()`.

![issue93q2](https://user-images.githubusercontent.com/36760800/72432614-c69d2c00-3797-11ea-8932-839e2d9d437b.png)

![issue93q21](https://user-images.githubusercontent.com/36760800/72432619-cd2ba380-3797-11ea-9f1a-65aa7c0a0002.png)

Please, also note that currently `investpy.search()` function is under development, so some results may differ or some searches may not be complete. We are working on it and the complete `investpy.search()` functionality will be included.

---

**Question 3**: Currency Crosses and Commodities missing data

The missing data you are presenting is not available neither among commodities nor currency crosses data, as it can be seen below. 

![issue93q31](https://user-images.githubusercontent.com/36760800/72434205-51335a80-379b-11ea-904e-9d127f99ef9a.png)

So on, `investpy.search()` function has been used to search those crosses among all Investing.com data using its search engine, and all the data is available for retrieval unless: *XNGUSD* and *XTIUSD*, which are not available in Investing.com since they seem to not exist.

![issue93q32](https://user-images.githubusercontent.com/36760800/72434211-542e4b00-379b-11ea-917c-4d659d5777d8.png)

When it comes to missing commodities, I guessed that when you typed *COTTEE* you meant *COFFEE*. Anyways, as you can see below all that information is available for retrieval.

![issue93q3](https://user-images.githubusercontent.com/36760800/72434181-42e53e80-379b-11ea-8384-013dd8320721.png)

---

 **Question 4**: Having problems with the script

Since as you have seen some Investing.com data is not stored among investpy's static data and even some times neither among Investing.com data; some errors may raise due to non-existent data, which can easily be solved using a **try-except** clause (you can find more information in the following url: https://docs.python.org/3/tutorial/errors.html#handling-exceptions).

Additionally, there is a huge mistake in your script since you are iterating with a FOR loop over three lists, where the loops are nested; but in your concrete case, you do not want to do that, you just want to take the product and the matching country; and iterate over pairs *product-country* for different intervals. The easiest way to develop a script in order to retrieve and store in CSV files all the information will be presented below.

```python3
import investpy
from datetime import date


today = date.today().strftime("%d/%m/%Y")

params = [
    {
        'name': 'ftse 100',
        'country': 'united kingdom'
    },
    {
        'name': 'ibex 35',
        'country': 'spain'
    },
    {
        'name': 'nikkei 225',
        'country': 'japan'
    },
    {
        'name': 'ftse mib',
        'country': 'italy'
    },
    {
        'name': 'hang seng',
        'country': 'hong kong'
    },
    {
        'name': 'dax',
        'country': 'germany'
    },
    {
        'name': 'cac 40',
        'country': 'france'
    },
    {
        'name': 'euro stoxx 50',
        'country': 'germany'
    },
    {
        'name': 's&p/asx 200',
        'country': 'australia'
    },
    {
        'name': 'ftse china 50 hkd',
        'country': 'china'
    },
]

intervals = ['Daily', 'Weekly', 'Monthly']

for param in params:
    for interval in intervals:
        result = investpy.get_index_historical_data(index=param['name'],
                                                    country=param['country'],
                                                    from_date='01/01/2001',
                                                    to_date=today,
                                                    interval=interval,
                                                    order='descending')

        result.to_csv(path_or_buf=param['name'].replace(' ', '_') + '_' + interval + '.csv')
```

---
Thank you for your feedback! Hope this helped you enough! :star: :octocat:

**Comment by delta-300** [comment]
import os
import glob
import pandas as pd
os.chdir(".")

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

I tried to merge everything into one master csv workbook, but it merge everything into one sheet and I was wondering... How could you optimize the output to merge all csv into one master workbook based on its interval and have it organized into different worksheets with their respective names?

For example:

1. Daily Workbook.csv
2. Weekly Workbook.csv
3. Monthly Workbook.csv

and each workbook contains (n) worksheets based on the script list specified

Thanks a lot in advance

**Comment by delta-300** [comment]
Hi Alvaro

Is it possible to skip the currency symbol column in the generated CSV reports?

**Comment by VoudourisAM** [comment]
Hi Alvaro, 

I try to extract crypto and I take:

RuntimeError: ERR#0085: crypto currency: btc, not found, check if it is correct.
or
ConnectionError: ERR#0015: error 403, try again later.

Thanks!
![Screenshot 2024-06-08 122647](https://github.com/alvarobartt/investpy/assets/79792887/ba9d10df-7595-49be-b7f9-b2b5dc882e7c)
![Screenshot 2024-06-08 122617](https://github.com/alvarobartt/investpy/assets/79792887/349e1259-5c1a-4dab-8b73-a33865bc4bdb)
