### ISSUE TITLE
Historical prices of fxfutures

### ISSUE THREAD

**Issue by ma73es** [alvarob96/investpy#96]
Hi, great job.

Is it possible to get Historical prices of fxfutures?
For example, EUR/USD future:
{"id_": 1055979, "name": "Euro Futures", "symbol": "ECM", "country": "europe", "tag": "eur-futures", "pair_type": "fxfuture", "exchange": "CME"}

investpy.search('ecm')[0].retrieve_historical_data(...) return None

**Comment by alvarob96** [comment]
Hi @ma73es! Appreciate your kind words.

It was not possible until now, since I was not handling the *fxfutures* properly, but now they are. So on, in the new version which will be released soon, now *fxfutures* search results will be available for data retrieval (both recent and historical).

The following `investpy.search()` functionality presented below will be available in 0.9.13 investpy's release.

![issue96](https://user-images.githubusercontent.com/36760800/72446118-3a006700-37b3-11ea-83fc-ab62ba5b5737.png)

Thank you! :star: :octocat:

**Comment by ma73es** [comment]
Thank you very much for you extra fast response.

**Comment by alvarob96** [comment]
I am re-opening this issue since **fxfutures data retrieval will be included in next investpy's release**. So on, stay tuned for future updates since fxfutures data retrieval is intented to be included in 0.9.14 release.
